config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  resources :communities do
    put :membership, on: :member
    get :members, on: :member
    resources :posts
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Do not put user routes above devise block or else bad things will happen.
  resources :users, :path => 'u', only: [:show] do
    put :follow, on: :member
    get 'relationships' => 'users#relationships'
    get 'following' => 'users#following'
  end
  #resources :follows
  get '/' => 'home#index'
  get 'faq' => 'home#faq'
  get 'admin' => 'admin#show'
  get 'about' => 'home#about'
  resources :books do
    put :favourite, on: :member
    resources :chapters
  end

  resources :reactions
  resources :feedbacks
  
  resources :chatrooms
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  has_many :chapters, dependent: :destroy
  has_many :comments, through: :chapters, dependent: :destroy
  validates :title, presence: true
  validates :rating, presence: true
  validates :status, presence: true
  validates :category, presence: true
  has_one_attached :image
  validates :image, file_size: { less_than_or_equal_to: 5.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png'] }
  has_rich_text :description
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  has_many :favourite_books
  has_many :favourited_by, through: :favourite_books, source: :user
  belongs_to :user
  has_many :reactions, through: :chapters
  has_many :feedbacks, through: :chapters
  is_impressionable :counter_cache => true, :column_name => :impressions_count, :unique => true
  scope :status, ->(status) { where status: status }
  scope :rating, ->(rating) { where rating: rating }
  scope :category, ->(category) { where category: category }

  # Finds books by tag, refers to models/tag.rb for the rest.
  scope :tags, -> (name){ joins(:tags).where(tags: {name: name}) }

  def self.search(search)
    if search
      book = Book.where("lower(title) LIKE ?", "%#{search.downcase}%")
      if book
        self.where(id: book)
      else
        Book.all
      end
    else
      Book.all
    end
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end
end

app/models/chapter.rb
# frozen_string_literal: true

class Chapter < ApplicationRecord
  include ActionText::Attachable
  belongs_to :book
  has_rich_text :content
  has_many :comments, as: :commentable
  has_many :reactions, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  def next
    Chapter.where("id > ? AND book_id = ?", id, book_id).first
  end
  def prev
    Chapter.where("id < ? AND book_id = ?", id, book_id).first
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/community.rb
class Community < ApplicationRecord
  # Communities have many little things. We need to delete the right things if
  # for some reason the community owner wishes to delete the whole thing. :(
  belongs_to :user
  has_many :community_members, dependent: :destroy
  has_many :users, through: :community_members
  has_many :community_member_bans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
  has_one_attached :image
  has_one_attached :background
  has_rich_text :description
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :background, file_size: { less_than_or_equal_to: 10.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png']}
  validates :image, file_size: { less_than_or_equal_to: 5.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png']}

end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
  belongs_to :community
  belongs_to :user
end

app/models/favourite_book.rb
class FavouriteBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :chapter
    belongs_to :user
  end
  

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: "user_id", class_name: "User"
  belongs_to :following, foreign_key: "following_id", class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :community
  belongs_to :user
  has_rich_text :content
  validates :content, presence: true
  has_many :comments, as: :commentable
end

app/models/reaction.rb
class Reaction < ApplicationRecord
    belongs_to :chapter
    belongs_to :user
    validates :emotion, presence: true
  end
  

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings
  has_many :books, through: :taggings
  scope :tag, -> (name){ where(name: name) }
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag, counter_cache: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  validates :image, file_size: { less_than_or_equal_to: 2.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png'] }
  has_many :books, dependent: :destroy
  has_many :chapters, through: :books
  has_many :community_members
  has_many :communities, through: :community_members
  has_many :favourite_books
  has_many :favourites, through: :favourite_books, source: :book
  has_many :comments
  has_many :community_member_bans
  has_many :posts, through: :communities
  has_many :reactions, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  # This piece of code is a bit complicated, but DRY and good practice.
  # This essentially creates a virtual table with the join table and messes with that.
  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :user_id, class_name: "Follow"
  has_many :following, through: :following_relationships, source: :following

  has_rich_text :biography
  validates_uniqueness_of :slug

  extend FriendlyId
  friendly_id :username, use: :slugged
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/book_helper.rb
# frozen_string_literal: true

module BookHelper
end

app/helpers/chapters_helper.rb
# frozen_string_literal: true

module ChaptersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/show.html.erb
<section class="admin">
  <h1>Admin Panel</h1>
  <h3>Users (<%= @users.count %>)</h3>
  <table class="green">
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Books</th>
      <th>Favourite Books</th>
      <th>Owned Communities</th>
      <th>Joined Communities</th>
      <th>Joined date</th>
    </tr>
    <% @users.each do |u| %>
      <tr>
        <td><%= link_to u.username, user_path(u) %></td>
        <td><%= u.firstname %> <%= u.lastname %></td>
        <td><%= u.email %></td>
        <td><%= u.books.count %></td>
        <td><%= u.favourite_books.count %></td>
        <td><%= @communities.where(user_id: u).count %></td>
        <td><%= u.community_members.count %></td>
        <td><%= u.created_at %></td>
      </tr>
    <% end %>
  </table>

  <h3>Books (<%= @books.count %>)</h3>
  <table class="red">
    <tr>
      <th>Title</th>
      <th>Views</th>
      <th>Category</th>
      <th>Rating</th>
      <th>Status</th>
      <th>Favourited</th>
      <th>Author</th>
      <th>Last Updated</th>
      <th>Created</th>
    </tr>
    <% @books.each do |b| %>
      <tr>
        <td><%= link_to b.title, book_path(b) %></td>
        <td><%= b.impressions_count %></td>
        <td><%= b.category %></td>
        <td><%= b.rating %></td>
        <td><%= b.status %></td>
        <td><%= b.favourited_by.count %></td>
        <td><%= link_to b.user.username, user_path(b.user) %></td>
        <td><%= b.updated_at %></td>
        <td><%= b.created_at %></td>
      </tr>
    <% end %>
  </table>

  <h3>Communities (<%= @communities.count %>)</h3>
  <table class="blue">
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Posts</th>
      <th>Members</th>
      <th>Banned Members</th>
      <th>Created</th>
    </tr>
    <% @communities.each do |c| %>
      <tr>
        <td><%= link_to c.name, community_path(c) %></td>
        <td><%= link_to c.user.username, user_path(c.user) %></td>
        <td><%= c.posts.count %></td>
        <td><%= c.community_members.count %></td>
        <td><%= c.community_member_bans.count %></td>
        <td><%= c.created_at %></td>
      </tr>
    <% end %>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeFiction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% if content_for?(:meta_og) %>
      <%= yield :meta_og %>
    <% else %>
      <meta property="og:title" content="FreeFiction" />
      <meta property="og:type" content="website" />
      <meta property="og:description" content="FreeFiction is a platform for readers and authors.
      It is about freedom to write and not be restricted for the content you write." />
      <meta property="og:url" content="https://freefiction.xyz" />
      <%= tag :meta, property: 'og:image', content: image_url('Fable.png') %>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'Fable.png' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Cantarell|Source+Serif+Pro|Pacifico' %>
    
  </head>

  <body>
    <button name="button" type="button" id="hamburger-trigger">
      <h1>
        <i class="material-icons" id="hamburger-icon">menu</i>
      </h1>
    </button>
    <div class="top-bar" id="sidebar" style="background: <%= current_user.panel_colour if user_signed_in? %>">
      <div id="top">
        <h6 style="position: absolute; left: 10px; top: 50px;">BETA v2.0</h6>
        <h1 style="font-family: 'Pacifico', cursive; font-weight: 500"><%= link_to 'FreeFiction', '/', class: 'linear-wipe' %></h1>
        
        <%= link_to '/' do %>
          <%= icon('fas', 'home') %>
          <p>Home</p>
        <% end %>
        <%= link_to communities_path do %>
          <%= icon('fas', 'user-friends') %>
          <p>Communities</p>
        <% end %>
        <%= link_to books_path do %>
          <%= icon('fas', 'search') %>
          <p>Browse</p>
        <% end %>
        <%= link_to 'https://discord.gg/ThTkAMG', target: '_blank' do %>
          <%= icon('fab', 'discord') %>
          <p>Discord server</p>
        <% end %>
      </div>
      <div id="bottom">  
        <% if user_signed_in? %>
          
          <div style="display: flex; justify-content: space-between">
            <%= link_to user_path(current_user) do %>
              <%= image_tag (current_user.image.variant(resize_to_limit: [30, 30])) if current_user.image.attached? %>
              <div>
                <p style="padding: 0px;">View Profile</p>
                <h6 style="font-weight: 100; padding: 0px;">@<%= current_user.username %></h6>
              </div>
            <% end %>
            <%= link_to destroy_user_session_path, title: "Sign Out", method: :delete do %>
              <i class="material-icons">exit_to_app</i>
            <% end %>
          </div>
          <div id="new-book-div">
          <%= link_to new_book_path, id: 'new-book' do %>
            <%= icon('fas', 'plus') %>
            <p>New Book</p>
          <% end %>
          </div>
          <div>
          <%= link_to user_path(current_user, options: '2') do %>
            <%= icon('fas', 'heart') %>
            <p>Favourited Stories</p>
          <% end %>
          <%= link_to user_path(current_user, options: '1') do %>
            <%= icon('fas', 'book') %>
            <p>My Stories</p>
          <% end %>
          <%= link_to user_path(current_user, options: '3') do %>
            <%= icon('fas', 'user-friends') %>
            <p>My Communities</p>
          <% end %>
          <div id="user-tray">
            <%= link_to edit_user_registration_path, title: "Settings" do %>
              <%= icon('fas', 'cog') %>
            <% end %>
            <%= link_to edit_user_registration_path, title: "Dark Mode" do %>
              <%= icon('fas', 'adjust') %>
            <% end %>
            <%= link_to edit_user_registration_path(:anchor => "panel_colour"), title: "Change Theme" do %>
              <%= icon('fas', 'palette') %>
            <% end %>
          </div>
          <%= link_to "Admin Panel", admin_path if current_user.role == 'Owner' %>
          </div>
        <% else %>
          <div class="user-bar">
            <%= link_to "Login", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          </div>
        <% end %>
        <div class="small-info">
          <p>
            <%= link_to 'About', about_path %> |
            <%= link_to 'FAQ', faq_path %> |
            <%= link_to 'Source code', 'https://gitlab.com/freefiction/freefiction' %>
            <%= link_to 'Patreon', 'https://www.patreon.com/user?u=25116515', target: '_blank' %>
          </p> 

        </div>
      </div>
    </div>
    
    
		<div class="main-content" id="content">
			<% if notice != nil %>
				<div class="notice">
					<strong><%= notice %></strong>
				</div>
			<% end %>
			<% if alert != nil %>
				<div class="alert">
					<strong><%= alert %></strong>
				</div>
			<% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_books.html.erb
<div class="x-book-child">

  <%= image_tag (book.image.variant(resize_to_limit: [100, 100])) if book.image.attached? %>
  <div class="x-book-child-text">
    <h1><%= link_to book.title, book_path(book)%></h1>
    <b><%= link_to book.user.username, user_path(book.user)%></b>
    <h5><%= book.impressionist_count(:filter=>:ip_address) %> views, <%= book.rating %></h5>
    <div class="reactions">
      <%# TODO sort by most occurring emotion %>
      <% book.reactions.distinct.limit(2).pluck(:emotion).each do |e| %>
        <div class="reaction-bubble">
          <p><span><%= book.reactions.where(emotion: e).size %>x</span> <%= e.titlecase %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>