config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  resources :communities do
    put :membership, on: :member
    get :members, on: :member
    resources :posts
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Do not put user routes above devise block or else bad things will happen.
  resources :users, :path => 'u', only: [:show] do
    put :follow, on: :member
    get 'relationships' => 'users#relationships'
    get 'following' => 'users#following'
  end
  #resources :follows
  get '/' => 'home#index'
  get 'faq' => 'home#faq'
  get 'admin' => 'admin#show'
  get 'about' => 'home#about'
  resources :books do
    put :favourite, on: :member
    resources :chapters
  end

  resources :reactions
  resources :feedbacks
  
  resources :chatrooms
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :image
  validates :image, file_size: { less_than_or_equal_to: 2.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png'] }
  has_many :books, dependent: :destroy
  has_many :chapters, through: :books
  has_many :community_members
  has_many :communities, through: :community_members
  has_many :favourite_books
  has_many :favourites, through: :favourite_books, source: :book
  has_many :comments
  has_many :community_member_bans
  has_many :posts, through: :communities
  has_many :reactions, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  # This piece of code is a bit complicated, but DRY and good practice.
  # This essentially creates a virtual table with the join table and messes with that.
  has_many :follows

  has_many :follower_relationships, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :user_id, class_name: "Follow"
  has_many :following, through: :following_relationships, source: :following

  has_rich_text :biography
  validates_uniqueness_of :slug

  extend FriendlyId
  friendly_id :username, use: :slugged
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    @user.image.attach(io: File.open("#{Rails.root}/app/assets/images/default.png"), filename: 'default.png', content_type: 'image/jpg')
    @user.colour = '#000000'
    @user.panel_colour = '#073b4c'
    @user.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[firstname lastname image biography colour panel_colour slug username reading_speed])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    if user_signed_in? && current_user.id == @user.id
      @books = @user.books
      @favourite_books = @user.favourite_books
    else user_signed_in? && current_user.id != @user.id || !user_signed_in?
      @books = @user.books.where(public: true)
      @favourite_books = @user.favourite_books.joins(:book).where(:books => {public: true})
    end
    

    @joined_communities = @user.community_members.all
    @owned_communities = Community.where(user_id: @user)
    @followers = @user.followers.all
    @following = @user.following.all
  end

  # PUT
  def follow
    @user = User.friendly.find(params[:id])
    type = params[:type]
    if type == "follow" && current_user != @user
      current_user.following << @user
      redirect_to user_path(@user)

    elsif type == "unfollow" && current_user != @user
      current_user.following.delete(@user)
      redirect_to user_path(@user)
    else
      redirect_to :back, notice: 'Invalid action!'
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/show.html.erb
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="@<%= @user.username %>'s Profile" />
  <meta property="og:description" content="<%= truncate(strip_tags(@user.biography.to_s), length: 200) %>" />
  <meta property="profile:username" content="@<%= @user.username %>" />
  <meta property="profile:firstname" content="@<%= @user.firstname %>" />
  <meta property="profile:lastname" content="@<%= @user.lastname %>" />
  <meta property="og:type" content="profile" />
  <%= tag :meta, property: 'og:image', content: "#{request.host_with_port}#{url_for(@user.image)}" %>
<% end %>
<div class="user-container">
  <div class="user-cover" style="background: <%= @user.colour %>">
    <div class="user-cover-relative">
      <%= image_tag (@user.image) if @user.image.attached? %>
      <div>
        <h1>
          <% if @user.firstname.nil? && (user_signed_in? && @user.id == current_user.id) %>
            <%= link_to "Add your name", edit_user_registration_path %>

          <% elsif @user.firstname.nil? %>
            No name
          <% else %>
            <%= @user.firstname %> <%= @user.lastname %>
          <% end %>
        </h1>
        <p>@<%= @user.username %> - <%= @user.role %></p>
      </div>
      <% if user_signed_in? && current_user.id != @user.id %>
        <% if current_user.following.find_by(id: @user.id) %>
          <%= link_to 'Unfollow', follow_user_path(@user, type: "unfollow"), method: :put, id: 'relationship-no' %>
        <% else %>
          <%= link_to 'Follow', follow_user_path(@user, type: "follow"), method: :put, id: 'relationship-yes' %>
        <% end %>
      <% end %>
      <% if user_signed_in? && @user.id == current_user.id %>
        <%= link_to 'Settings', edit_user_registration_path, class: 'primary-btn' %>
      <% end %>
    </div>
  </div>
  <div class="user-info">
    <div class="user-details">
      <p><%= @user.biography %></p>
      <p>Joined <%= @user.created_at.strftime("%B %Y") %></p>
     
    </div>
  </div>
  <div class="user-stats">
    <div class="stat-item" onclick="currentSlide(1)">
      <p>Books</p>
      <strong><%= @books.count %></strong> 
    </div>
    <div class="stat-item" onclick="currentSlide(2)">
      <p>Favourite Books</p>
      <strong><%= @favourite_books.count %></strong> 
    </div>
    <div class="stat-item" onclick="currentSlide(3)">
      <p>Communities</p>
      <strong><%= @owned_communities.count + @user.community_members.count %></strong>    
    </div>
    <div class="stat-item" onclick="currentSlide(4)">
      <p>Following</p>
      <strong><%= @user.following.count %></strong>   
    </div>
    <div class="stat-item" onclick="currentSlide(5)">
      <p>Followers</p>
      <strong><%= @user.followers.count %></strong>
    </div>
  </div>

  <div class="user-stuff">

    <div class="statsSlides fade">
      <% if user_signed_in? && current_user.id == @user.id %>
        <h3>Your books</h3>
      <% else %>
        <h3>Books made by this author</h3>
      <% end %>
      <div class="user-books">
        <% @books.each do |b| %>
          <div class="user-items">
            <div class="user-book-img">
              <%= image_tag (b.image) if b.image.attached? %>
            </div>
            <strong><%= link_to b.title, book_path(b)%></strong>
            <br>
            <p><%= b.impressionist_count(:filter=>:ip_address) %> views</p>
          </div>
        <% end %>
      </div>

      
    </div>

    <div class="statsSlides fade">
      <h3>Favourite books</h3>
      <div class="user-books">
        <% @favourite_books.each do |f| %>
          <div class="user-items">
            <div class="user-book-img">
              <%= image_tag (f.book.image) if f.book.image.attached? %>
            </div>
            <strong><%= link_to f.book.title, book_path(f.book_id)%></strong>
            <br>
            <p><%= f.book.impressionist_count(:filter=>:ip_address) %> views</p>
          </div>
        <% end %>
      </div>
    </div>

    <div class="statsSlides fade">
      <h3>Owned communities</h3>
      <div class="user-memberships">
        <div class="communities-parent">
          <% @owned_communities.each do |c| %>
            <div class="community-item">
              <div class="community-img">
                <div>
                  <%= image_tag (c.image) if c.image.attached? %>
                  <strong><%= link_to c.name, community_path(c) %></strong>
                </div>
                  <% if user_signed_in? %>
                    <% if c.community_members.find_by(user_id: current_user.id, community_id: c.id) %>
                      <%= link_to 'Leave', membership_community_path(c, type: "leave"), class: 'del-btn', method: :put %>
                    <% elsif c.community_member_bans.find_by(user_id: current_user.id, community_id: c.id) %>
                    <% elsif c.user.id == current_user.id %>
                    <% else %>
                      <%= link_to 'Join', membership_community_path(c, type: "join"), class: 'join-btn', method: :put %>
                    <% end %>
                <% end %>
              </div>
              <div class="text">
                <p>Members: <%= c.community_members.count %></p>
                <%= truncate(strip_tags(c.description.to_s), length: 110) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <h3>Joined communities</h3>
      <div class="user-memberships">
        <div class="communities-parent">
          <% @joined_communities.each do |c| %>
            <div class="community-item">
              <div class="community-img">
                <div>
                  <%= image_tag (c.community.image) if c.community.image.attached? %>
                  <strong><%= link_to c.community.name, community_path(c) %></strong>
                </div>
                  <% if user_signed_in? %>
                    <% if c.community.community_members.find_by(user_id: current_user.id, community_id: c.id) %>
                      <%= link_to 'Leave', membership_community_path(c, type: "leave"), class: 'del-btn', method: :put %>
                    <% elsif c.community.community_member_bans.find_by(user_id: current_user.id, community_id: c.id) %>
                    <% elsif c.community.user.id == current_user.id %>
                    <% else %>
                      <%= link_to 'Join', membership_community_path(c, type: "join"), class: 'join-btn', method: :put %>
                    <% end %>
                <% end %>
              </div>
              <div class="text">
                <p>Members: <%= c.community.community_members.count %></p>
                <%= truncate(strip_tags(c.community.description.to_s), length: 110) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="statsSlides fade">
      <h3>Following</h3>
      <% @following.each do |f| %>
        <div class="follow-item">
          <%= image_tag (f.image) if f.image.attached? %>
          <strong><%= link_to f.username, user_path(f) %></strong>
        </div>
      <% end %>
    </div>

    <div class="statsSlides fade">
      <h3>Followers</h3>
      <% @followers.each do |f| %>
        <div class="follow-item">
          <%= image_tag (f.image) if f.image.attached? %>
          <strong><%= link_to f.username, user_path(f) %></strong>
        </div>
      <% end %>
    </div>

    
    
  </div>
</div>
<script>
<% if request.params[:options].nil? %>
let slideIndex = 1;
<% else %>
let slideIndex = <%= request.params[:options] %>;
<% end %>
showSlides(slideIndex);

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {

  let slides = document.getElementsByClassName("statsSlides");
  
  let statItems = document.getElementsByClassName("stat-item");
  
  if (n > slides.length) {
  	slideIndex = 1
  } 
  
  if (n < 1) {
  	slideIndex = slides.length
  }
  
  for (let i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (let i = 0; i < statItems.length; i++) {
      statItems[i].className = statItems[i].className.replace(" active", "");
  }
  
  slides[slideIndex-1].style.display = "block";  
  statItems[slideIndex-1].className += " active";
}
</script>