config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  resources :communities do
    put :membership, on: :member
    get :members, on: :member
    resources :posts
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Do not put user routes above devise block or else bad things will happen.
  resources :users, :path => 'u', only: [:show] do
    put :follow, on: :member
    get 'relationships' => 'users#relationships'
    get 'following' => 'users#following'
  end
  #resources :follows
  get '/' => 'home#index'
  get 'faq' => 'home#faq'
  get 'admin' => 'admin#show'
  get 'about' => 'home#about'
  resources :books do
    put :favourite, on: :member
    resources :chapters
  end

  resources :reactions
  resources :feedbacks
  
  resources :chatrooms
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
# frozen_string_literal: true

class Chapter < ApplicationRecord
  include ActionText::Attachable
  belongs_to :book
  has_rich_text :content
  has_many :comments, as: :commentable
  has_many :reactions, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  def next
    Chapter.where("id > ? AND book_id = ?", id, book_id).first
  end
  def prev
    Chapter.where("id < ? AND book_id = ?", id, book_id).first
  end
end

app/controllers/chapters_controller.rb
# frozen_string_literal: true

class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def new
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.new
  end

  def create
    @book = Book.find(params[:book_id])
    if user_signed_in? && @book.user_id == current_user.id
      @chapter = @book.chapters.create(chapter_params)
      if @chapter.save
        redirect_to book_chapter_path(@book, @chapter)
      else
        logger.debug @chapter.errors.full_messages
        redirect_to books_path
      end
    else
      redirect_to 'index', notice: "You are not allowed to create chapters on #{@book.user.username}'s book!"
    end
  end

  def show
    @book = Book.find(params[:book_id])
    if @book.public || user_signed_in? && current_user.id == @book.user.id
      @chapter = Chapter.find(params[:id])
      @comments = @chapter.comments.all
      @commentable_type = "Chapter"
      @commentable_id = @chapter.id
      @reaction = Reaction.new
      @reactions = @chapter.reactions.all
      @feedback = Feedback.new
      @feedbacks = @chapter.feedbacks.all 
      @created_feedback = @chapter.feedbacks.find_by(user_id: current_user.id) if user_signed_in?
    else 
      render 'index', alert: 'The writer has made this chapter hidden.'
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
    if @chapter.book.user_id != current_user.id
      redirect_to books_path, alert: "You are not allowed to edit other people's books"
    end
  end

  def update
    @book = Book.find(params[:book_id])
    if user_signed_in? && @book.user_id == current_user.id
      @chapter = @book.chapters.find(params[:id])
      if @chapter.update(chapter_params)
        redirect_to book_chapter_path(@book, @chapter)
      else
        render 'edit'
        logger.debug @chapter.errors.full_messages
      end
    else
      redirect_to 'index', notice: "You are not allowed to update chapters on #{@book.user.username}'s book!"
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    if user_signed_in? && @book.user_id == current_user.id
      @chapter = @book.chapters.find(params[:id])
      @chapter.destroy
      redirect_to book_path(@book)
    else
      redirect_to 'index', notice: "You are not allowed to destroy chapters on #{@book.user.username}'s book!"
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:book_id, :title, :content)
  end
end

app/helpers/chapters_helper.rb
# frozen_string_literal: true

module ChaptersHelper
end

app/views/chapters/edit.html.erb
<%= form_with model: @chapter, url: { action: "update" }, local: true do |form| %>
<div class="chapter-topbar">
  
  <p>Currently editing <%= link_to @chapter.book.title, book_path(@chapter.book.id) %></p>
  <div>
    <p><%= link_to 'Discard Changes', url_for(:back) %></p>
    <%= form.submit "Create", class: "publish-btn" %>
  </div>
</div>
<div class="paper">
    <div class="paper-title">
      <%= form.text_field :title, autofocus: true %>
    </div>
    <div class="paper-content">
      <%= form.rich_text_area :content %>
    </div>
    <p>

    </p>
  <% end %>
</div>

app/views/chapters/new.html.erb
<%= form_with(model: @chapter, url: [@book, @chapter], local: true) do |form| %>
<div class="chapter-topbar">
  
  <p>You are creating a new chapter for <%= link_to @chapter.book.title, book_path(@chapter.book.id) %></p>
  <div>
    <p><%= link_to 'Discard Changes', url_for(:back) %></p>
    <%= form.submit "Create", class: "publish-btn" %>
  </div>
</div>
<div class="paper">
    <div class="paper-title">
      <%= form.text_field :title, autofocus: true, value: 'New Chapter Title' %>
    </div>
    <div class="paper-content">
      <%= form.rich_text_area :content, placeholder: 'Once upon a time ago...' %>
    </div>
    <p>

    </p>
  <% end %>
</div>

app/views/chapters/show.html.erb
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="<%= @chapter.title + ' - ' + @book.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:published_time" content="<%= @book.created_at.strftime('%Y-%m-%d %H:%M') %>" />
  <meta property="og:author" content="<%= @book.user.username %>" />
  <meta property="og:description" content="<%= truncate(strip_tags(@chapter.content.to_s), length: 50) %>" />
  <% if @book.image %>
      <%= tag :meta, property: 'og:image', content: "#{request.host_with_port}#{url_for(@book.image)}" %>
  <% end %>
<% end %>
<div class="book-bar">
  <div class="book-dropdown">
      <div class="chapter-back">
        <%= link_to book_path(@book) do %>
          <i class="material-icons">arrow_back_ios</i>
        <% end %>
      </div>
    <button name="button" type="button" id="book-dropdown">
      <%= image_tag (@book.image.variant(resize_to_limit: [50, 50])) if @book.image.attached? %>
      <div class="flex-column">
        <h3><%= @book.title %></h3>
        <p>By <%= link_to @chapter.book.user.username, user_path(@book.user) %></p>
      </div>
      <i class="material-icons">arrow_drop_down</i>
    </button>
    <div id="book-dropdown-content">
      <% @book.chapters.each do |c| %>
        <%= link_to book_chapter_path(@book.id, c.id) do %>
          <div class="dropdown-child">
            <%= c.title %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="controls">
    <% if user_signed_in? && current_user.id == @book.user_id %>
      <%= link_to "Edit", edit_book_chapter_path(@book, @chapter) %>
      <%= link_to 'New Chapter', new_book_chapter_path(@book) %>
      <%= link_to 'Delete',
         book_chapter_url(@book, @chapter),
         method: :delete,
         data: { confirm: 'Are you sure you want to delete this chapter?' } %>
    <% end %>
  </div>
</div>
<div class="progress-container">
  <div class="progress-bar" id="myBar"></div>
</div>
<section>
  <div class="paper" id="chapter">
    <div class="paper-title">
      <h1><%= @chapter.title %></h1>
    </div>
    <div class="paper-content">
      <%= @chapter.content %>
    </div>
  </div>
  <div class="pagination">
    <% counter = 0 %>
    <div class="pagination-item">
      <%= link_to 'Prev', book_chapter_path(@book.id, @chapter.prev) if @chapter.prev %>
      <% @book.chapters.each do |c| %>
        <% counter += 1 %>
        <%= link_to counter, book_chapter_path(@book.id, c.id) %>
      <% end %>
      <%= link_to 'Next', book_chapter_path(@book.id, @chapter.next) if @chapter.next %>
    </div>
  </div>
	<div class="feedback">
		<h2>Feedback</h2>
    <div class="feedback-container">
      <% if user_signed_in? && @created_feedback %>
        <div class="created-feedback">
					<strong>Your feedback</strong>
					<table>
						<% [:opening, :character_development, :story_logic, :dialogue, :originality, :conclusion, :grammar, :show_not_tell].each do |f| %>
							<tr>
								<td><%= f.to_s.humanize %></td>
								<td>
									<% (@created_feedback[f].to_i).times do |n| %>
										<%= icon('fas', 'star') %>
									<% end %>
								</td>
							</tr>
						<% end %>
					</table>
          <%= link_to 'Delete your feedback', feedback_path(@created_feedback.id, :chapter_id => @chapter.id), method: :delete %>
        </div>
			<% elsif user_signed_in? %>
				<div class="new-feedback">
					<p>Let the writer know how their chapter is</p>
					<%= form_with model: @feedback,  local: true do |r| %>
						<% [:opening, :character_development, :story_logic, :dialogue, :originality, :conclusion, :grammar, :show_not_tell].each do |f| %>
							
							<div class="rate">
							<%= "#{f.to_s.humanize}" %>
								<% 5.times.reverse_each do |c| %>
									<%= r.radio_button f, (c + 1) %>
									<%= r.label f, "#{c + 1} stars", title: 'text', for: "feedback_#{f}_#{c + 1}" %>
								<% end %>
								</div>
						<% end %>   
						<%= hidden_field_tag 'chapter_id', @chapter.id %>
						<%= r.submit 'Submit Feedback', class: "publish-btn" %>
					<% end %>
				</div>
			
			<% else %>
				<div class="new-feedback">
				<i>You need to be logged in to give feedback</i>
				</div>
			<% end %>
			<div class="received-feedback">
				<strong>Feedback average (<%= @chapter.feedbacks.count %>)</strong>
				<table>
					<% [:opening, :character_development, :story_logic, :dialogue, :originality, :conclusion, :grammar, :show_not_tell].each do |f| %>
						<tr>
							<td><%= f.to_s.humanize %></td>
							<td><%= @chapter.feedbacks.average(f) %>/5</td>
						</tr>
					<% end %>
				</table>
			</div>
    </div>

    <div class="reaction-container">
      <h2>Reactions</h2>
      <div class="reactions">
        <% @reactions.distinct.pluck(:emotion).each do |e| %>
          <div class="reaction-bubble">
            <p><span><%= @reactions.where(emotion: e).size %>x</span> <%= e.titlecase %></p>
          </div>
        <% end %>
        <% if @chapter.reactions.empty? %>
          <i>There are no reactions yet. Be the first to react to this chapter and give the writer some feedback</i>
        <% end %>
      </div>
      <% if user_signed_in? && current_user.reactions.find_by(chapter_id: @chapter.id) %>
        <h3>Your reaction</h3>
        <p>This chapter made you <%= @reactions.find_by(user_id: current_user.id).emotion %>.</p>
        <%= link_to reaction_path(@reactions.find_by(user_id: current_user.id), :chapter_id => @chapter.id), method: :delete do %>
          <p>Delete</p>
        <% end %>
			<% elsif user_signed_in? %>
        <strong>React to this chapter</strong>
        <%= form_with model: @reaction,  local: true do |r| %>
          <%= r.radio_button :emotion, 'happy' %>
          <%= r.label :emotion_happy, 'Happy' %>
          <%= r.radio_button :emotion, 'excited' %>
          <%= r.label :emotion_excited, 'Excited' %>
          <%= r.radio_button :emotion, 'sad' %>
          <%= r.label :emotion_sad, 'Sad' %>
          <%= r.radio_button :emotion, 'bored' %>
          <%= r.label :emotion_bored, 'Bored' %>
          <%= r.radio_button :emotion, 'angry' %>
          <%= r.label :emotion_angry, 'Angry' %>
          <%= r.radio_button :emotion, 'scared' %>
          <%= r.label :emotion_scared, 'Scared' %>
          <%= r.radio_button :emotion, 'love' %>
          <%= r.label :emotion_love, 'Love' %>
          <%= r.radio_button :emotion, 'laugh' %>
          <%= r.label :emotion_laugh, 'Laugh' %>
          <%= r.radio_button :emotion, 'confused' %>
          <%= r.label :emotion_confused, 'Confused' %>
          
          <%= hidden_field_tag 'chapter_id', @chapter.id %>
          <%= r.submit 'React', class: "save-btn" %>
				<% end %>
			<% else %>
					<i>You need to be logged in to react to this chapter</i>
      <% end %>
    </div>
  </div>

  <div class="comments-container" id="comments">
    <h2>Comments</h2>
    <% @comments.each do |comment| %>
      <div class="comment-child">
        <div class="commenter">
          <%= image_tag (comment.user.image.variant(resize_to_limit: [50, 50])) if comment.user.image.attached? %>
          <strong><%= link_to comment.user.username, user_path(comment.user) %></strong>
          <p> said on <%= comment.created_at.strftime("%B %d %Y") %></p>
        </div>
        <div class="comment-body">
          <p><%= simple_format(comment.body) %></p>
          <% if (user_signed_in? && current_user == comment.user) || (user_signed_in? && current_user.id == @book.user_id) %>
            <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        </div>
      </div>
		<% end %>
		<% if !user_signed_in? %>
			<i>You need to be logged in to comment</i>
		<% end %>
    <div class="comment-box">
      <% if current_user %>
        <%= render partial: 'comments/form', locals: { commentable: @chapter } %>
      <% end %>
    </div>
  </div>
</section>
<script>
document.getElementById("content").addEventListener("scroll", myFunction);

function myFunction() {
  let winScroll = document.getElementById('content').scrollTop || document.documentElement.scrollTop;
  let height = document.getElementById('chapter').scrollHeight - document.documentElement.clientHeight;
  let scrolled = (winScroll / height) * 100;
  document.getElementById("myBar").style.width = scrolled + "%";
}


document.addEventListener('DOMContentLoaded', function () {
  let bookdropdown = document.getElementById("book-dropdown");
  let userdropdown = document.getElementById("user-dropdown");
  let bookcontent = document.getElementById("book-dropdown-content");
  let usercontent = document.getElementById("user-dropdown-content");

  function bookShowList() {
    if (bookcontent.style.display == '' || bookcontent.style.display == "none"){
      bookcontent.style.display = "flex";
    } else {
      bookcontent.style.display = "none";
    }

  }

  function userShowList() {
    if (usercontent.style.display == '' || usercontent.style.display == "none"){
      usercontent.style.display = "flex";
    } else {
      usercontent.style.display = "none";
    }

  }

  if (userdropdown) {
    userdropdown.addEventListener("click", userShowList);
  }
  if (bookdropdown) {
    bookdropdown.addEventListener("click", bookShowList);
  }

})


</script>