config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments
  resources :communities do
    put :membership, on: :member
    get :members, on: :member
    resources :posts
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Do not put user routes above devise block or else bad things will happen.
  resources :users, :path => 'u', only: [:show] do
    put :follow, on: :member
    get 'relationships' => 'users#relationships'
    get 'following' => 'users#following'
  end
  #resources :follows
  get '/' => 'home#index'
  get 'faq' => 'home#faq'
  get 'admin' => 'admin#show'
  get 'about' => 'home#about'
  resources :books do
    put :favourite, on: :member
    resources :chapters
  end

  resources :reactions
  resources :feedbacks
  
  resources :chatrooms
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
  # Communities have many little things. We need to delete the right things if
  # for some reason the community owner wishes to delete the whole thing. :(
  belongs_to :user
  has_many :community_members, dependent: :destroy
  has_many :users, through: :community_members
  has_many :community_member_bans, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
  has_one_attached :image
  has_one_attached :background
  has_rich_text :description
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :background, file_size: { less_than_or_equal_to: 10.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png']}
  validates :image, file_size: { less_than_or_equal_to: 5.megabytes },
                     file_content_type: { allow: ['image/jpeg', 'image/png']}

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  def index
    @communities = Community.all
  end
  def new
    @community = Community.new
  end
  def show
    @community = Community.friendly.find(params[:id])
    @post = @community.posts.new
    @posts = @community.posts.all
    # commentable type is defined here but the ID is in the view because the id
    # changes upon each loop through the posts and we need to associate the
    #comment with the correct post by it's ID.
    @commentable_type = "Post"
  end
  def create
    if user_signed_in?
      @community = Community.new(community_params.merge(user_id: current_user.id))
      unless @community.image.attached?
        @community.image.attach(io: File.open("#{Rails.root}/app/assets/images/community-default.png"), filename: 'community-default.png', content_type: 'image/jpg')
      end
      if @community.save
        redirect_to community_path(@community)
      else
        render 'index'
      end
    else
      render 'index', notice: "Please sign in to create a community"
    end
  end

  def edit
    @community = Community.friendly.find(params[:id])
    if @community.user_id != current_user.id
      redirect_to books_path, alert: "You are not the owner of this community!"
    end
  end

  def update
    @community = Community.friendly.find(params[:id])
    if user_signed_in? && @community.user_id == current_user.id
      if @community.update(community_params)
        redirect_to @community
      else
        render 'edit'
      end
    else
      redirect_to 'index', notice: 'You are not the owner of this community!'
    end
  end

  # Not be confused with membership. This is a members GET path.
  def members
    @community = Community.friendly.find(params[:id])
    @members = @community.community_members.all
    @banned_members = @community.community_member_bans.all
  end

  # This function takes in a PUT request with URL parameters matching by type.
  def membership
    @community = Community.friendly.find(params[:id])
    type = params[:type]
    if type == "join" && !@community.community_member_bans.find_by(user_id: current_user.id, community_id: @community.id)
      current_user.community_members.create(community_id: @community.id, user_id: current_user.id)
      redirect_to community_path(@community)

    elsif type == "leave"
      @community.community_members.find_by(user_id: current_user.id, community_id: @community.id).destroy
      redirect_to community_path(@community)

    elsif type == "kick" && @community.user_id == current_user.id
      @community.community_members.find_by(user_id: params[:who], community_id: @community.id).destroy
      redirect_to community_path(@community)

    elsif type == "ban" && @community.user_id == current_user.id
      # kick the user and then add them to ban list.
      @community.community_members.find_by(user_id: params[:who], community_id: @community.id).destroy
      @community.community_member_bans.create(community_id: @community.id, user_id: params[:who])
      redirect_to members_community_path(@community)

    elsif type == "unban" && @community.user_id == current_user.id
      @community.community_member_bans.find_by(community_id: @community.id, user_id: params[:who]).destroy
      redirect_to members_community_path(@community)

    else
      # Don't trust the user!
      redirect_to @community, notice: 'Unauthorised requests detected.'

    end
  end

  def destroy
    @community = Community.friendly.find(params[:id])
    if user_signed_in? && @community.user_id == current_user.id
      @community.destroy
      redirect_to communities_path
    else
      redirect_to 'index', notice: "You are not allowed to destroy someone's community!"
    end
  end

  private
  def community_params
    params.require(:community).permit(:name, :description, :image, :color, :background)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<section class="community-form">
  <%= form_with model: @community, class: 'big-form', local: true do |form| %>

    <% if current_page?(action: :new) %>
      <h1>Start your own community!</h1>
    <% else current_page?(action: :edit) %>
      <h1>Edit your community</h1>
    <% end %>

    <div class="field">
      <h3><%= form.label :name %></h3>
      <%= form.text_field :name, autofocus: true, class: "text-field", required: true %>
    </div>

    <div class="field" id="user-bio-edit">
      <h3><%= form.label :description %></h3>
      <div>
        <%= form.rich_text_area :description %>
      </div>
    </div>

    <div class="field">
      <h3><%= form.label :image %></h3>
      <div>
        <%= image_tag (@community.image) if @community.image.attached? %>
        <%= form.file_field :image %>
      </div>
    </div>


    <div class="field">
      <div>
        <h3><%= form.label 'Banner color' %></h3>
        <p>Select a colour for the banner.</p>
      </div>
      <%= form.color_field :color, autofocus: true, class: "text-field", required: true %>
    </div>

    <div class="field">
      <h3><%= form.label 'Banner image' %></h3>
      <div>
        <%= image_tag (@community.background) if @community.background.attached? %>
        <%= form.file_field :background %>
      </div>
    </div>
    <p>Recommended banner size is at least 1000x600 pixels.</p>

    <p>
      <% if current_page?(action: :new) %>
        <%= form.submit 'Create', class: 'save-btn' %>
      <% else %>  
        <%= form.submit 'Update', class: 'save-btn' %>
      <% end %>
      <%= link_to 'Discard changes', url_for(:back) %>
    </p>
  <% end %>
</section>

app/views/communities/edit.html.erb
<%= render 'form' %>

app/views/communities/index.html.erb
<section>
  <div class="community-header">
    <h1>Communities</h1>
    <% if user_signed_in? %>
      <%= link_to 'Start a New Community', new_community_path, class: 'primary-btn' %>
    <% end %>
  </div>
  <div class="communities-parent" style="overflow: auto">
    <table style="min-width: 768px;">
      <tr style="background: #073b4c; color: white">
        <th></th>
        <th></th>
        <th>Community</th>
        <th>About</th>
        <th>Members</th>
        <th>Topics</th>
        <th>Comments</th>
      </tr>
      <% @communities.each do |c| %>
        <tr>
          <td style="color: gold; text-align: center"><%= c.status == 'official' ? icon('fas', 'star') : '' %></td>
          <td style="width: 50px"><%= image_tag (c.image) if c.image.attached? %></td>
          <td><%= link_to c.name, community_path(c) %></td>
          <td><%= strip_tags(c.description.to_s) %></td>
          <td style="text-align: center"><%= c.community_members.count %></td>
          <td style="text-align: center"><%= c.posts.count %></td>
          <td style="text-align: center"><%= c.comments.count %></td>
        </tr>
      
      <% end %>
    </table>
  </div>
</section>

app/views/communities/members.html.erb
<section>
  <%= link_to 'Go back', community_path(@community) %>
  <h2>Members</h2>
  <div class="member-list">
    <% @members.each do |m| %>
      <div class="member-item">
        <div style="display: flex; align-items: center">
          <%= image_tag (m.user.image) if m.user.image.attached? %>
          <h3><%= link_to m.user.username, user_path(m.user) %></h3>
        </div>
        <p>
          <% if user_signed_in? && @community.user_id == current_user.id %>
            <%= link_to 'Kick', membership_community_path(@community, type: "kick", who: m.user.id ), method: :put %>
            <br>
            <%= link_to 'Ban', membership_community_path(@community, type: "ban", who: m.user.id ), method: :put %>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? && @community.user_id == current_user.id %>
    <h2>Banned Members</h2>
    <div class="members-list">
      
      <% @banned_members.each do |m| %>
        <div class="member-item">
          <div style="display: flex; align-items: center">
            <%= image_tag (m.user.image) if m.user.image.attached? %>
            <h3><%= link_to m.user.username, user_path(m.user) %></h3>
          </div>
          <% if @community.user_id == current_user.id %>
            <%= link_to 'Unban', membership_community_path(@community, type: "unban", who: m.user.id ), method: :put %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</section>

app/views/communities/new.html.erb
<%= render 'form' %>

app/views/communities/show.html.erb
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="<%= @community.name %> - FreeFiction" />
  <meta property="og:description" content="<%= truncate(strip_tags(@community.description.to_s), length: 50) %>" />
  <meta property="og:type" content="profile" />
  <%= tag :meta, property: 'og:image', content: "#{request.host_with_port}#{url_for(@community.image)}" %>
<% end %>

<div class="community-container">
  <div class="community-cover" style="background-color: <%= @community.color %>;">
      <%= image_tag (@community.background) if @community.background.attached? %>
  </div>
  <div class="community-info">
    <%= image_tag (@community.image) if @community.image.attached? %>
    <div class="community-idk">
      <h1><%= @community.name %></h1>
      <div class="community-buttons">
        <% if user_signed_in? %>
          <strong>
            <% if @community.community_members.find_by(user_id: current_user.id, community_id: @community.id) %>
              <%= link_to 'Leave Community', membership_community_path(@community, type: "leave"), class: 'del-btn', method: :put %>
            <% elsif @community.user_id == current_user.id %>
              <%= link_to 'Edit community', edit_community_path(@community), class: 'primary-btn' %>
            <% elsif @community.community_member_bans.find_by(user_id: current_user.id, community_id: @community.id) %>
              You have been banned.
            <% else %>
              <%= link_to 'Join Community', membership_community_path(@community, type: "join"), class: 'join-btn', method: :put %>
            <% end %>
          </strong>
        <% end %>
        <%= link_to 'View Members', members_community_path(@community), class: 'secondary-btn' %>
      </div>
    </div>
    <div style="width: 100%"></div>
    <%= @community.description %>
  </div>
  <div class="community-post-container">
    <div class="community-new-post">
      <% if user_signed_in? %>
        <% if current_user.id == @community.user_id || @community.community_members.find_by(user_id: current_user.id)%>
          <%= render partial: 'posts/form' %>
        <% end %>
      <% end %>
    </div>
    <% if !@posts.present? %>
      <h3 style="color: grey">There does not appear to be any posts here.</h3>
    <% end %>
    <% @posts.each do |p| %>
      <div class="community-post">
        <div class="community-poster">
          <div>
            <%= image_tag (p.user.image) if p.user.image.attached? %>
            <div>
              <h4><%= link_to p.user.username, user_path(p.user) %></h4>
              <h5>on <%= p.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h5>
            </div>
          </div>
          <div>
            <% if user_signed_in? && (p.user_id == current_user.id || @community.user_id == current_user.id)%>
              <h6><%= link_to 'Delete', community_post_path(p), method: :delete, data: {confirm: 'Are you sure?'} %>
              <%= link_to 'Edit', edit_community_post_path(p) %></h6>
            <% else user_signed_in? && @community.user_id == current_user.id %>
              <h6><%= link_to 'Delete', community_post_path(p), method: :delete, data: {confirm: 'Are you sure?'} %></h6>
            <% end %>
          </div>
        </div>
        <div class="community-post-content">
          <%= p.content %>
        </div>
      </div>
      <% p.comments.each do |c| %>
        <div class="community-post-comment">
          <%= image_tag (c.user.image) if c.user.image.attached? %>
          <div class="post-comment-content">
            <div class="post-comment-head">
              <strong><%= link_to c.user.username, user_path(c.user) %></strong>
              <% if user_signed_in? && (c.user_id == current_user.id || @community.user_id == current_user.id)%>
                <h6><%= link_to 'Delete', comment_path(c), method: :delete, data: {confirm: 'Are you sure?'} %></h6>
              <% end %>
            </div>
            <p><%= c.body %></p>
          </div>
        </div>
      <% end %>
      <div class="new-community-post-comment">
        <% if user_signed_in? && (@community.community_members.find_by(user_id: current_user.id, community_id: @community.id) || @community.user_id == current_user.id)%>
            <% @commentable_id = p.id %>
            <%= render partial: 'comments/form', locals: { commentable: p } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>